# Server Configuration
server.port=8082

# Application Name
spring.application.name=admin-service

# Database Configuration (H2 for now, or match your DB)
#spring.datasource.url=
#spring.datasource.driverClassName=
#spring.datasource.username=
#spring.datasource.password=
#spring.jpa.database-platform=
#spring.h2.console.enabled=
#spring.jpa.hibernate.ddl-auto=update

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# JWT Configuration
jwt.secret=renalapplicationwithmicroservicesextendedforsecurekeylength

# Logging Configuration
logging.level.com.admin_service=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
