BEGIN TRANSACTION;

DO $$
BEGIN

    CREATE TABLE IF NOT EXISTS rental_app_service.roles (
        id INTEGER PRIMARY KEY NOT NULL,
        name VARCHAR(255) NOT NULL
    );

END;
$$;
COMMIT TRANSACTION;